### ISSUE TITLE
Mejoras Diseño - Home

### ISSUE THREAD

**Issue by EduFullTip** [EduFullTip/FullTip#2]
- Aumentar scroll categorías al hacer scroll
- Dejar definido botón flotante
- Cambiar logo automoción por el que no esta selecionado
- Maquetar collection view iphone 6+

**Comment by rafilla2tb** [comment]
Aumentar scroll categorías al hacer scroll -->OK
    Dejar definido botón flotante-->OK
    Cambiar logo automoción por el que no esta selecionado-->OK, Pero ahora sale por ver el funcionamiento del scroll, despues no tendra scroll
    Maquetar collection view iphone 6+-->OK
